//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NotJustSokoban.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("NotJustSokoban.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///	&quot;mapFileNames&quot; : [
        ///		&quot;Level1&quot;,
        ///		&quot;Level3&quot;,
        ///		&quot;Level7&quot;,
        ///	],
        ///	&quot;fileExtension&quot; : &quot;.txt&quot;,
        ///	&quot;mapsType&quot; : &quot;file/JSON&quot;,
        ///	&quot;directory&quot; : &quot;..\\..\\Levels\\FileLevels&quot;,
        ///}.
        /// </summary>
        internal static string EasyMaps {
            get {
                return ResourceManager.GetString("EasyMaps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///	&quot;mapFileNames&quot; : [
        ///		&quot;TestLevel1&quot;,
        ///		&quot;TestLevel2&quot;,
        ///		&quot;TestLevel3&quot;,
        ///		&quot;TestLevel4&quot;,
        ///		&quot;TestLevel5&quot;,
        ///		&quot;TestLevel6&quot;,
        ///		&quot;TestLevel7&quot;,
        ///	],
        ///	&quot;fileExtension&quot; : &quot;.txt&quot;,
        ///	&quot;mapsType&quot; : &quot;hardcodedTest&quot;,
        ///	&quot;directory&quot; : &quot;..\\..\\Levels\\HardcodedLevels&quot;,
        ///}.
        /// </summary>
        internal static string HardcodedLevels {
            get {
                return ResourceManager.GetString("HardcodedLevels", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///	&quot;mapFileNames&quot; : [
        ///		&quot;Level5&quot;,
        ///	],
        ///	&quot;fileExtension&quot; : &quot;.txt&quot;,
        ///	&quot;mapsType&quot; : &quot;file/JSON&quot;,
        ///	&quot;directory&quot; : &quot;..\\..\\Levels\\FileLevels&quot;,
        ///}.
        /// </summary>
        internal static string HardMaps {
            get {
                return ResourceManager.GetString("HardMaps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///	&quot;mapFileNames&quot; : [
        ///		
        ///	],
        ///	&quot;fileExtension&quot; : &quot;.txt&quot;,
        ///	&quot;mapsType&quot; : &quot;file/JSON&quot;,
        ///	&quot;directory&quot; : &quot;..\\..\\Levels\\FileLevels&quot;,
        ///}.
        /// </summary>
        internal static string InsaneMaps {
            get {
                return ResourceManager.GetString("InsaneMaps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///	&quot;gameObjects&quot; : {
        ///		&quot;player&quot; : [[12,9],],
        ///		&quot;box&quot; : [
        ///			[3,8],
        ///			[6,3],
        ///			[6,5],
        ///			[6,8],
        ///			[8,4],
        ///			[8,5],
        ///		],
        ///		&quot;target&quot; : [
        ///			[17,7],
        ///			[17,8],
        ///			[17,9],
        ///			[18,7],
        ///			[18,8],
        ///			[18,9],
        ///		],
        ///		&quot;wall&quot; : [
        ///			[1,6],
        ///			[1,7],
        ///			[1,8],
        ///			[1,9],
        ///			[2,9],
        ///			[3,9],
        ///			[4,9],
        ///			[5,9],
        ///			[5,10],
        ///			[5,11],
        ///			[6,11],
        ///			[7,11],
        ///			[8,11],
        ///			[9,11],
        ///			[10,11],
        ///			[11,11],
        ///			[11,10],
        ///			[11,9],
        ///			[12,10],
        ///			[13,10],
        ///			[13,9],
        ///			[14,9],
        ///			[14,10] [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Level1 {
            get {
                return ResourceManager.GetString("Level1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///	&quot;gameObjects&quot; : {
        ///		&quot;player&quot; : [[7,6],],
        ///		&quot;box&quot; : [
        ///			[5,4],
        ///			[5,3],
        ///			[7,3],
        ///		],
        ///		&quot;target&quot; : [
        ///			[4,3],
        ///			[6,5],
        ///			[7,7],
        ///		],
        ///		&quot;wall&quot; : [
        ///			[1,1],
        ///			[2,1],
        ///			[3,1],
        ///			[4,1],
        ///			[5,1],
        ///			[6,1],
        ///			[7,1],
        ///			[8,1],
        ///			[8,2],
        ///			[8,3],
        ///			[8,4],
        ///			[8,5],
        ///			[8,6],
        ///			[8,7],
        ///			[8,8],
        ///			[7,8],
        ///			[6,8],
        ///			[5,8],
        ///			[4,8],
        ///			[3,8],
        ///			[3,7],
        ///			[3,6],
        ///			[3,5],
        ///			[4,5],
        ///			[5,5],
        ///			[2,5],
        ///			[1,5],
        ///			[1,4],
        ///			[1,3],
        ///			[1,2],
        ///			[3,3],
        ///		] [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Level2 {
            get {
                return ResourceManager.GetString("Level2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///	&quot;gameObjects&quot; : {
        ///		&quot;player&quot; : [[2,4],],
        ///		&quot;box&quot; : [
        ///			[3,4],
        ///			[4,4],
        ///			[5,4],
        ///			[7,3],
        ///		],
        ///		&quot;target&quot; : [
        ///			[8,3],
        ///			[8,4],
        ///			[8,5],
        ///			[8,6],
        ///		],
        ///		&quot;wall&quot; : [
        ///			[1,2],
        ///			[1,3],
        ///			[1,4],
        ///			[1,5],
        ///			[2,5],
        ///			[2,6],
        ///			[2,7],
        ///			[3,7],
        ///			[4,7],
        ///			[5,7],
        ///			[5,6],
        ///			[5,5],
        ///			[6,6],
        ///			[7,6],
        ///			[8,6],
        ///			[9,6],
        ///			[10,6],
        ///			[10,5],
        ///			[10,4],
        ///			[10,3],
        ///			[10,2],
        ///			[10,1],
        ///			[9,1],
        ///			[8,1],
        ///			[7,1],
        ///			[6,1],
        ///			[6,2],
        ///			[6,3],
        ///			[5,3] [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Level3 {
            get {
                return ResourceManager.GetString("Level3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///	&quot;gameObjects&quot; : {
        ///		&quot;player&quot; : [[15,3],],
        ///		&quot;box&quot; : [
        ///			[15,5],
        ///			[15,7],
        ///			[15,9],
        ///			[15,11],
        ///			[15,13],
        ///			[11,3],
        ///			[10,4],
        ///			[8,6],
        ///			[5,6],
        ///			[5,7],
        ///			[4,11],
        ///			[6,12],
        ///			[6,13],
        ///			[8,11],
        ///			[10,12],
        ///			[10,10],
        ///			[11,11],
        ///			[12,12],
        ///			[10,14],
        ///			[9,14],
        ///		],
        ///		&quot;target&quot; : [
        ///			[17,5],
        ///			[17,7],
        ///			[17,9],
        ///			[17,11],
        ///			[17,13],
        ///			[17,14],
        ///			[18,5],
        ///			[18,6],
        ///			[18,7],
        ///			[18,8],
        ///			[18,9],
        ///			[18,10],
        ///			[18,11],
        ///			[18,12],
        ///			[18,13], [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Level4 {
            get {
                return ResourceManager.GetString("Level4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///	&quot;gameObjects&quot; : {
        ///		&quot;player&quot; : [[5,6],],
        ///		&quot;box&quot; : [
        ///			[3,4],
        ///			[3,5],
        ///		],
        ///		&quot;target&quot; : [
        ///			[5,2],
        ///			[5,3],
        ///		],
        ///		&quot;wall&quot; : [
        ///			[1,4],
        ///			[1,5],
        ///			[1,6],
        ///			[1,7],
        ///			[2,7],
        ///			[3,7],
        ///			[4,7],
        ///			[5,7],
        ///			[6,7],
        ///			[7,7],
        ///			[7,6],
        ///			[7,5],
        ///			[7,4],
        ///			[8,4],
        ///			[8,3],
        ///			[8,2],
        ///			[8,1],
        ///			[7,1],
        ///			[6,1],
        ///			[5,1],
        ///			[4,1],
        ///			[3,1],
        ///			[2,1],
        ///			[2,2],
        ///			[2,3],
        ///			[2,4],
        ///			[4,3],
        ///			[4,4],
        ///			[5,4],
        ///		],
        ///	},
        ///	
        ///	&quot;levelData&quot; : {
        ///		&quot;size&quot; : [8,7 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Level5 {
            get {
                return ResourceManager.GetString("Level5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///	&quot;gameObjects&quot; : {
        ///		&quot;player&quot; : [[4,6],],
        ///		&quot;box&quot; : [
        ///			[2,3],
        ///			[3,3],
        ///			[4,3],
        ///			[3,5],
        ///			[4,5],
        ///		],
        ///		&quot;target&quot; : [
        ///			[2,4],
        ///			[3,4],
        ///			[4,4],
        ///			[5,4],
        ///			[5,5],
        ///		],
        ///		&quot;wall&quot; : [
        ///			[1,1],
        ///			[1,2],
        ///			[1,3],
        ///			[1,4],
        ///			[1,5],
        ///			[1,6],
        ///			[1,7],
        ///			[2,7],
        ///			[3,7],
        ///			[4,7],
        ///			[5,7],
        ///			[6,7],
        ///			[6,6],
        ///			[6,5],
        ///			[6,4],
        ///			[6,3],
        ///			[6,2],
        ///			[6,1],
        ///			[5,1],
        ///			[4,1],
        ///			[3,1],
        ///			[2,1],
        ///		],
        ///	},
        ///	
        ///	&quot;levelData&quot; : {
        ///		&quot;size&quot; : [6,7],
        ///		&quot;orig [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Level6 {
            get {
                return ResourceManager.GetString("Level6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///	&quot;gameObjects&quot; : {
        ///		&quot;player&quot; : [[6,2],],
        ///		&quot;box&quot; : [
        ///			[4,3],
        ///			[5,4],
        ///			[3,5],
        ///		],
        ///		&quot;target&quot; : [
        ///			[2,3],
        ///			[4,3],
        ///			[4,5],
        ///		],
        ///		&quot;wall&quot; : [
        ///			[1,1],
        ///			[1,2],
        ///			[1,3],
        ///			[1,4],
        ///			[1,5],
        ///			[1,6],
        ///			[2,6],
        ///			[3,6],
        ///			[4,6],
        ///			[5,6],
        ///			[6,6],
        ///			[7,6],
        ///			[7,5],
        ///			[7,4],
        ///			[7,3],
        ///			[7,2],
        ///			[7,1],
        ///			[6,1],
        ///			[5,1],
        ///			[4,1],
        ///			[3,1],
        ///			[2,1],
        ///			[2,2],
        ///			[3,2],
        ///			[5,3],
        ///			[6,5],
        ///		],
        ///	},
        ///	
        ///	&quot;levelData&quot; : {
        ///		&quot;size&quot; : [7,6],
        ///		&quot;orig [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Level7 {
            get {
                return ResourceManager.GetString("Level7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///	&quot;mapFileNames&quot; : [
        ///		&quot;Level2&quot;,
        ///		&quot;Level4&quot;,
        ///		&quot;Level5&quot;,
        ///	],
        ///	&quot;fileExtension&quot; : &quot;.txt&quot;,
        ///	&quot;mapsType&quot; : &quot;file/JSON&quot;,
        ///	&quot;directory&quot; : &quot;..\\..\\Levels\\FileLevels&quot;,
        ///}.
        /// </summary>
        internal static string ModerateMaps {
            get {
                return ResourceManager.GetString("ModerateMaps", resourceCulture);
            }
        }
    }
}
